version: '3.5'

services:
  lumen:
    ports:
      - "4001:4001"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S 0.0.0.0:4001 -t public
    restart: always